// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40B-KHbXnl71McuIz7XZm5CGfI5AbD7k',
    appId: '1:417279404472:web:83e04a79855c6b1793874d',
    messagingSenderId: '417279404472',
    projectId: 'new-books-app-d2116',
    authDomain: 'new-books-app-d2116.firebaseapp.com',
    storageBucket: 'new-books-app-d2116.firebasestorage.app',
    measurementId: 'G-ZY0Q3XQ0JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAou8qgjUbwbQAy8vt2caLg05jzhCL1y3o',
    appId: '1:417279404472:android:f3929925fbadf51893874d',
    messagingSenderId: '417279404472',
    projectId: 'new-books-app-d2116',
    storageBucket: 'new-books-app-d2116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjmmGnCMDamYo4TJoL30Zd1BtNwtCwPQ',
    appId: '1:417279404472:ios:b0b02513e8da040893874d',
    messagingSenderId: '417279404472',
    projectId: 'new-books-app-d2116',
    storageBucket: 'new-books-app-d2116.firebasestorage.app',
    iosBundleId: 'com.example.interviewTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjmmGnCMDamYo4TJoL30Zd1BtNwtCwPQ',
    appId: '1:417279404472:ios:b0b02513e8da040893874d',
    messagingSenderId: '417279404472',
    projectId: 'new-books-app-d2116',
    storageBucket: 'new-books-app-d2116.firebasestorage.app',
    iosBundleId: 'com.example.interviewTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC40B-KHbXnl71McuIz7XZm5CGfI5AbD7k',
    appId: '1:417279404472:web:d3eb011b330311ee93874d',
    messagingSenderId: '417279404472',
    projectId: 'new-books-app-d2116',
    authDomain: 'new-books-app-d2116.firebaseapp.com',
    storageBucket: 'new-books-app-d2116.firebasestorage.app',
    measurementId: 'G-0LSYWXYZ59',
  );
}
